version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Backend/Src/Presentation/WebApi/Dockerfile
    depends_on:
      - tripdb
      - consul
    networks:          
      - backend
      - frontend

  tripdb:  
    image: mongo:latest
#    volumes:
#      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - frontend

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    networks:
      - frontend

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      - backend
      - frontend
  
  seq:
    image: datalust/seq:latest
    ports:
      - 3000:80
      - 5341:5341
    networks:
      - backend
      - frontend
    environment:
      ACCEPT_EULA: Y

networks:
  backend:
  frontend:
