version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Backend/Src/Presentation/WebApi/Dockerfile
    depends_on:
      - tripdb
      - consul
    networks:          
      - backend
      - frontend

  tripdb:  
    image: mongo:latest
    networks:
      - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - frontend

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    networks:
      - frontend

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      - backend
      - frontend
  
  seq:
    image: datalust/seq:latest
    networks:
      - backend
      - frontend

networks:
  backend:
  frontend:
