version: '3.4'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EnableServiceDiscovery=true
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://webapi:80
      - ServiceConfig__serviceName=webapi
      - ServiceConfig__serviceId=webapi-v1
    ports:
      - "80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44357
    ports:
      - "58045:80"
      - "44357:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  
  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EnableServiceDiscovery=true
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://identityserver:80
      - ServiceConfig__serviceName=identityserver
      - ServiceConfig__serviceId=identityserver-v1
    ports:
      - "80"

  consul:   
    ports:    
      - "8500:8500"